; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.3 on Sun Oct 03 2021 11:01:59 GMT-0600 (Mountain Daylight Time)
; Wait for set temperatures to be reached
M116 P0

